import Head from "next/head";
import Navbar from "../components/Navbar";

export default function AboutUs() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <h1>About Us</h1>
    </div>
  );
}
